apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./deploy-api.yaml
  - ./svc-api.yaml

configMapGenerator:
  - name: nginx-confd-templates
    files:
      - default.conf.template=./nginx-default.conf.template

  - name: coredns
    files:
      - ./Corefile
